# This is a basic workflow to help you get started with Actions

name: POI CICD

env:
  poi_path: apis/pos/**
  registry: docker.pkg.github.com
  repository: mike-westaway/openhack-devops/api-poi
  docker_path: apis/po/web
  staging_url: https://openhackdnt2onp8poi-staging.azurewebsites.net
  prod_url: https://openhackdnt2onp8poi.azurewebsites.net
  resource_group: openhackdnt2onp8rg
  webapp_name: openhackdnt2onp8rg
  build_name: POI
  
  # Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml
  pull_request:
    branches: [ main ]
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.202'
          
      - name: Add Code Coverage Tools
        working-directory: apis/poi/tests/UnitTests
        run: dotnet add package coverlet.msbuild
        
      - name: Install Dependencies
        run: dotnet restore apis/poi/web/*.csproj
      
      - name: .Net Build Web
        run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj
        
      - name: .Net Build Unit Tests
        run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj
      
      - name: .Net Test
        run: dotnet test --no-retsore --verbosity normal apis/poi/tests/UnitTests /p:CollectCoverege=true /p:CoverletOutput=lcov/ /p:CoverletOutputFormat=lcov
      
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: apis/poi/tests/UnitTests/lcov/coverage.info
            base-path: apis/poi
            flag-name: Unit 
  
 
